/// Sri Lanka — 9 Provinces → 25 Districts → Areas
/// Each province maps to its districts, and each district maps to a list of
/// towns / areas commonly used for salon searches.

const Map<String, Map<String, List<String>>> slLocations = {
  // ── 1. Western Province ───────────────────────────────────────────────────
  'Western': {
    'Colombo': [
      'Colombo Fort',
      'Pettah',
      'Kollupitiya',
      'Bambalapitiya',
      'Wellawatte',
      'Dehiwala',
      'Mount Lavinia',
      'Nugegoda',
      'Maharagama',
      'Kotte',
      'Rajagiriya',
      'Battaramulla',
      'Borella',
      'Maradana',
      'Narahenpita',
      'Kirulapone',
      'Kohuwala',
      'Nawala',
      'Hokandara',
      'Malabe',
      'Kaduwela',
      'Athurugiriya',
      'Piliyandala',
      'Kesbewa',
      'Moratuwa',
      'Ratmalana',
      'Angoda',
      'Kotikawatta',
      'Mulleriyawa',
      'Kolonnawa',
      'Hanwella',
      'Padukka',
      'Avissawella',
      'Homagama',
    ],
    'Gampaha': [
      'Gampaha',
      'Negombo',
      'Wattala',
      'Ja-Ela',
      'Kadawatha',
      'Kelaniya',
      'Ragama',
      'Kandana',
      'Peliyagoda',
      'Kiribathgoda',
      'Mahara',
      'Dompe',
      'Biyagama',
      'Minuwangoda',
      'Divulapitiya',
      'Nittambuwa',
      'Mirigama',
      'Katunayake',
      'Seeduwa',
      'Veyangoda',
      'Attanagalla',
    ],
    'Kalutara': [
      'Kalutara',
      'Panadura',
      'Horana',
      'Bandaragama',
      'Beruwala',
      'Aluthgama',
      'Matugama',
      'Agalawatta',
      'Dodangoda',
      'Ingiriya',
      'Bulathsinhala',
      'Palindanuwara',
      'Wadduwa',
      'Payagala',
    ],
  },

  // ── 2. Central Province ───────────────────────────────────────────────────
  'Central': {
    'Kandy': [
      'Kandy City',
      'Peradeniya',
      'Katugastota',
      'Gampola',
      'Nawalapitiya',
      'Kadugannawa',
      'Pilimatalawa',
      'Akurana',
      'Wattegama',
      'Gelioya',
      'Kundasale',
      'Pujapitiya',
      'Teldeniya',
      'Galaha',
      'Deltota',
      'Udunuwara',
      'Harispattuwa',
      'Hatharaliyadda',
      'Doluwa',
      'Yatinuwara',
    ],
    'Matale': [
      'Matale',
      'Dambulla',
      'Sigiriya',
      'Galewela',
      'Naula',
      'Ukuwela',
      'Rattota',
      'Pallepola',
      'Yatawatta',
      'Laggala',
      'Wilgamuwa',
    ],
    'Nuwara Eliya': [
      'Nuwara Eliya',
      'Hatton',
      'Talawakele',
      'Ginigathena',
      'Maskeliya',
      'Kotagala',
      'Dickoya',
      'Ragala',
      'Lindula',
      'Walapane',
      'Hanguranketha',
      'Rikillagaskada',
    ],
  },

  // ── 3. Southern Province ──────────────────────────────────────────────────
  'Southern': {
    'Galle': [
      'Galle Fort',
      'Galle City',
      'Unawatuna',
      'Hikkaduwa',
      'Ambalangoda',
      'Karapitiya',
      'Imaduwa',
      'Baddegama',
      'Elpitiya',
      'Balapitiya',
      'Bentota',
      'Habaraduwa',
      'Akmeemana',
      'Yakkalamulla',
    ],
    'Matara': [
      'Matara',
      'Weligama',
      'Dikwella',
      'Akuressa',
      'Hakmana',
      'Deniyaya',
      'Kamburupitiya',
      'Devinuwara',
      'Mirissa',
      'Thihagoda',
      'Malimbada',
      'Pitabeddara',
      'Kotapola',
      'Pasgoda',
    ],
    'Hambantota': [
      'Hambantota',
      'Tangalle',
      'Tissamaharama',
      'Ambalantota',
      'Beliatta',
      'Weeraketiya',
      'Kataragama',
      'Sooriyawewa',
      'Lunugamvehera',
      'Angunakolapelessa',
      'Okewela',
    ],
  },

  // ── 4. Northern Province ──────────────────────────────────────────────────
  'Northern': {
    'Jaffna': [
      'Jaffna',
      'Nallur',
      'Chavakachcheri',
      'Point Pedro',
      'Kopay',
      'Chankanai',
      'Sandilipay',
      'Manipay',
      'Tellippalai',
      'Karainagar',
      'Kayts',
      'Velanai',
      'Delft',
    ],
    'Kilinochchi': [
      'Kilinochchi',
      'Pallai',
      'Paranthan',
      'Poonakary',
      'Karachchi',
    ],
    'Mannar': ['Mannar', 'Nanattan', 'Madhu', 'Murunkan', 'Musali', 'Mantai'],
    'Vavuniya': [
      'Vavuniya',
      'Nedunkerni',
      'Cheddikulam',
      'Vavuniya South',
      'Omanthai',
    ],
    'Mullaitivu': [
      'Mullaitivu',
      'Puthukkudiyiruppu',
      'Oddusuddan',
      'Thunukkai',
      'Maritimepattu',
    ],
  },

  // ── 5. Eastern Province ───────────────────────────────────────────────────
  'Eastern': {
    'Batticaloa': [
      'Batticaloa',
      'Kattankudy',
      'Eravur',
      'Valachchenai',
      'Kaluwanchikudy',
      'Chenkalady',
      'Oddamavady',
      'Manmunai',
      'Paddippalai',
      'Koralai Pattu',
    ],
    'Ampara': [
      'Ampara',
      'Kalmunai',
      'Akkaraipattu',
      'Sammanthurai',
      'Sainthamaruthu',
      'Dehiattakandiya',
      'Uhana',
      'Mahaoya',
      'Pottuvil',
      'Arugam Bay',
      'Addalachchenai',
      'Ninthavur',
      'Damana',
    ],
    'Trincomalee': [
      'Trincomalee',
      'Kinniya',
      'Muttur',
      'Kantale',
      'Gomarankadawala',
      'Seruvila',
      'Thampalakamam',
      'Kuchchaveli',
      'Nilaveli',
    ],
  },

  // ── 6. North Western Province ─────────────────────────────────────────────
  'North Western': {
    'Kurunegala': [
      'Kurunegala',
      'Kuliyapitiya',
      'Narammala',
      'Wariyapola',
      'Pannala',
      'Nikaweratiya',
      'Mawathagama',
      'Polgahawela',
      'Ibbagamuwa',
      'Galgamuwa',
      'Rideegama',
      'Bingiriya',
      'Alawwa',
      'Ganewatta',
      'Dambadeniya',
      'Hettipola',
      'Maho',
    ],
    'Puttalam': [
      'Puttalam',
      'Chilaw',
      'Wennappuwa',
      'Marawila',
      'Anamaduwa',
      'Nattandiya',
      'Dankotuwa',
      'Mundel',
      'Kalpitiya',
      'Mahakumbukkadawala',
      'Pallama',
    ],
  },

  // ── 7. North Central Province ─────────────────────────────────────────────
  'North Central': {
    'Anuradhapura': [
      'Anuradhapura',
      'Kekirawa',
      'Medawachchiya',
      'Tambuttegama',
      'Mihintale',
      'Eppawala',
      'Galenbindunuwewa',
      'Nochchiyagama',
      'Talawa',
      'Kahatagasdigiliya',
      'Thirappane',
      'Nuwaragam Palatha',
      'Rambewa',
      'Ipalogama',
      'Padaviya',
      'Horowpathana',
      'Kebithigollewa',
    ],
    'Polonnaruwa': [
      'Polonnaruwa',
      'Kaduruwela',
      'Medirigiriya',
      'Hingurakgoda',
      'Minneriya',
      'Lankapura',
      'Dimbulagala',
      'Elahera',
      'Welikanda',
      'Thamankaduwa',
    ],
  },

  // ── 8. Uva Province ───────────────────────────────────────────────────────
  'Uva': {
    'Badulla': [
      'Badulla',
      'Bandarawela',
      'Haputale',
      'Ella',
      'Welimada',
      'Passara',
      'Mahiyanganaya',
      'Hali-Ela',
      'Uva Paranagama',
      'Lunugala',
      'Kandaketiya',
      'Soranathota',
      'Rideemaliyadda',
    ],
    'Monaragala': [
      'Monaragala',
      'Wellawaya',
      'Buttala',
      'Bibile',
      'Kataragama',
      'Medagama',
      'Siyambalanduwa',
      'Madulla',
      'Thanamalwila',
      'Sewanagala',
    ],
  },

  // ── 9. Sabaragamuwa Province ──────────────────────────────────────────────
  'Sabaragamuwa': {
    'Ratnapura': [
      'Ratnapura',
      'Balangoda',
      'Pelmadulla',
      'Eheliyagoda',
      'Kuruwita',
      'Embilipitiya',
      'Kalawana',
      'Godakawela',
      'Kahawatta',
      'Nivithigala',
      'Opanayaka',
      'Ayagama',
      'Weligepola',
      'Atakalampanna',
    ],
    'Kegalle': [
      'Kegalle',
      'Mawanella',
      'Rambukkana',
      'Warakapola',
      'Ruwanwella',
      'Dehiowita',
      'Deraniyagala',
      'Yatiyantota',
      'Aranayake',
      'Galigamuwa',
      'Bulathkohupitiya',
    ],
  },
};
